language: node_js
node_js:
  - '6'
  - '4'

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: NGn87q+6FfLVKwuC0j0IbqT5uJgZUTEiSZwSMzZnVpnI0f27sT4cRQDEJpfKge9GJoMyPUNR8rfYJVX5zSLEV+jXV6sCxnQO3PDNSPJyvBjQuuiNF/ZNItEc+TEg3QCiv2s9PjcVQfc2r7F6+tVG5Ce+vfTpsgRZplfAG3PAYtSePHUTbWhDvARq5eTMW++P1oqaxhL0KxGuQMKBqjU2S+LAt1ky7UdhZqu6+6LY1oaaTDjl8Yvn/GdRklD39aWW6vx2Z2kvuFW2Stq9vtQ0GFZdt8ttTbn2l8nwAuOluIFvseooTtClDfcVDutQD42TD5/pRGjSHSaNmGbMCEcMKxQ55e4gY5KUkWdEMXIq0u9gr5xQa63pq/tQoSni/9YOs4jtFLYYU0ZWr6zY6cpqka7q8uxE22P61abLTIlEbSGatNsTgKoX5Upnj2U/L8BKbcWG4YHwXdlG6F7qyMIxTArYd9aja3nTLgXzwhT2f0WgwwB+vDv5LoQHNm2H2VXrS4rwQ5lhD5DGzFvQFl8WS+p7EHLibHN2s+ZiU8k+LvVN88THDlun+G5jVAoJAkg83OVguU284BZC+6kHbxMtjMm3T9lgAAXp+mcWaL0Jopm+JTlRvnT5hKyJVklKtWB0Gn4ox73qsSAc7OrX2P7ZrZ6ztITWNA6LdPquQVYZBYA=
    on_success: change
    on_failure: always

deploy:
  provider: npm
  api_key: "dkVrLG+KnnFb/NZCRIeu76N5KqjO028bl6L9u9xQDQmP59cqwNi+iaGLMcT4DxLCb3vc+b4WykFqSGqrVjPbG5u2ixs3w2e7hQ097TtyDVgM/vZvCaLpXJm2ieSHbGyU2i4rSZdkvB/OIITvL7cAT6b2irOsz9kkRbCFModC+KzgsQoYuVC2yMDunihPwgYqQTB0Idm2wTXU3Ix2WOYUGH6iWsIBVCvUlH6uLryolUI9Ie3223ainxaqOe6UF8tQLpsSqZXvTUVih4xrY+559VRgt02PwApaK4g8mH6j3uv/y2zJ0bE/iBkcjPUH11FCrEMqk2+eqBwoyG45j536YjRaHSZOiI/wjaTjrkCjo05rPCtm149dKdLpQ6RUoVk+CeB8L40+nFl82IUnmDYDqgIrtOJYTvJlHnn2jyo55bzjvcNIcwyR73fNsc2448OkmGeYzwhM9gE/Glbkp45/ZXX//Y117wvvHEXldeEOCec216nvKuFZ/Ub13ZL5pfH1S7gavgQq4CHktfiH/hyFn4gzEDVjzDHnVCfH/ELmXBXGu+292XJxJX+tFKLnkx/P3uSjOtMZhRbm08Kc+fzj6nfoacBgL3BLEZdCVmzJZClycR5CJa+V0ju9AiIbbiT5qZ8fU2VUDeUnVmZJhd6bCkSy09Pa6HxkW6rHoEqLogE="
  on:
    tags: true
    node: '6'
