language: node_js
node_js:
  - '6'
  - '4'

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: NGn87q+6FfLVKwuC0j0IbqT5uJgZUTEiSZwSMzZnVpnI0f27sT4cRQDEJpfKge9GJoMyPUNR8rfYJVX5zSLEV+jXV6sCxnQO3PDNSPJyvBjQuuiNF/ZNItEc+TEg3QCiv2s9PjcVQfc2r7F6+tVG5Ce+vfTpsgRZplfAG3PAYtSePHUTbWhDvARq5eTMW++P1oqaxhL0KxGuQMKBqjU2S+LAt1ky7UdhZqu6+6LY1oaaTDjl8Yvn/GdRklD39aWW6vx2Z2kvuFW2Stq9vtQ0GFZdt8ttTbn2l8nwAuOluIFvseooTtClDfcVDutQD42TD5/pRGjSHSaNmGbMCEcMKxQ55e4gY5KUkWdEMXIq0u9gr5xQa63pq/tQoSni/9YOs4jtFLYYU0ZWr6zY6cpqka7q8uxE22P61abLTIlEbSGatNsTgKoX5Upnj2U/L8BKbcWG4YHwXdlG6F7qyMIxTArYd9aja3nTLgXzwhT2f0WgwwB+vDv5LoQHNm2H2VXrS4rwQ5lhD5DGzFvQFl8WS+p7EHLibHN2s+ZiU8k+LvVN88THDlun+G5jVAoJAkg83OVguU284BZC+6kHbxMtjMm3T9lgAAXp+mcWaL0Jopm+JTlRvnT5hKyJVklKtWB0Gn4ox73qsSAc7OrX2P7ZrZ6ztITWNA6LdPquQVYZBYA=
    on_success: change
    on_failure: always

deploy:
  provider: npm
  api_key: secure: "GW+qWC1lEg6xgEpYNX777JB/hVliQ6r38KvWm2Nb4x0We6+MRAPg7O+tX7G0AYNKSXUeWZuXqVkjwEJOCUXU4Dr56f1y7LuvE40GjFF9Yx/jo84zzU+J8g899fPeeDLcSQVm0zXk0yn4wicbfy1TozlDIKEIfjAk+ODG2M754CY+xV+PIHXtu4Goii1hoL2LiOpuDrb9GHMAjHhxhR9MiwICDuKnOnUnxppxOlwM6f6riZMrpO8iCQP0UgmXanv2Srr7ymLEatL3X/sS/+nZqAPSQhbJm/wqBaGeTAKQKqgOUo0+olmtP594iq6ohDznJAX9XBE4T5O6iTDA2AN/wI+KdHb62gjkfSvrl58oV+Ja81wWdCcFFu870kcPTXRjZG6aQi3UUsTuq/B6+lqxEpZMBZl9tg0MNWowRN9XJ2+u3UP1H+RAOU4cv+/S05Wvt9QNx1sS0h5sLojjj47kAUUX8T/qjHQPb6mWZ0Hw6UuSCin3kGuJ3U22yRqYtivJjdmELMPxGnNf0AT1M7raZHjxSrv98GDQkujWcBsvqdC0k1CefGE86pbXbT+qT91w007JxZSUXowt74qlIe7CZ/62ZEDVG27v6Y+21lWeSUxlAAOimZD72yzXa/5TYKw8TxUZnPAxo/LIIXcrer2WpKqU+t98O+m1YOfHQjHzz3M="
  on:
    tags: true
    node: '6'
